// this is where the file is located
package main.picturepoker;

// this is effectively the C include thing
import main.picturepoker.util.DataTransferObject;

public class Player implements DataTransferObject {
    //Special player ID - not used in the sample code
    private int p_ID;
    private String name;
    private String password;
    private int gamesPlayed;
    private int firsts;
    private int seconds;
    private int thirds;
    private int fourths;
    private int dollars;

    //Per game info - Zeroed out, and refreshed upon each new game
    private int tokens;
    private int bet;
    private int rounds_won;

    //Autogenerated getters and setters


    @Override
    public int getID() {
        return p_ID;
    }

    public void setID(int playerID) {
        this.p_ID = p_ID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getGamesPlayed() {
        return gamesPlayed;
    }

    public void setGamesPlayed(int gamesPlayed) {
        this.gamesPlayed = gamesPlayed;
    }

    public int getFirsts() {
        return firsts;
    }

    public void setFirsts(int firsts) {
        this.firsts = firsts;
    }

    public int getSeconds() {
        return seconds;
    }

    public void setSeconds(int seconds) {
        this.seconds = seconds;
    }

    public int getThirds() {
        return thirds;
    }

    public void setThirds(int thirds) {
        this.thirds = thirds;
    }

    public int getFourths() {
        return fourths;
    }

    public void setFourths(int fourths) {
        this.fourths = fourths;
    }

    public int getDollars() {
        return dollars;
    }

    public void setDollars(int dollars) {
        this.dollars = dollars;
    }

    public int getTokens() {
        return tokens;
    }

    public void setTokens(int tokens) {
        this.tokens = tokens;
    }

    public int getBet() {
        return bet;
    }

    public void setBet(int bet) {
        this.bet = bet;
    }

    public int getRounds_won() {
        return rounds_won;
    }

    public void setRounds_won(int rounds_won) {
        this.rounds_won = rounds_won;
    }

    //ToString thing

    @Override
    public String toString() {
        return "Player{" +
                "name='" + name + '\'' +
                ", password='" + password + '\'' +
                ", gamesPlayed=" + gamesPlayed +
                ", firsts=" + firsts +
                ", seconds=" + seconds +
                ", thirds=" + thirds +
                ", fourths=" + fourths +
                ", dollars=" + dollars +
                ", tokens=" + tokens +
                ", bet=" + bet +
                ", rounds_won=" + rounds_won +
                '}';
    }
}