services:
  db:
    build: Database SQL/
    image: postgres
    volumes:
      - $HOME/srv/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=picturepoker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    restart: always
  app:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=picturepoker
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    expose:
      - 8080:8080
    ports:
      - 8080:8080
    depends_on:
      - db
  ui:
    build: PicturePokerReact/luigipoker/
    ports:
      - 80:3000
    depends_on:
      - app