services:
  db:
    build: Database SQL/
    image: luigipoker.azurecr.io/db
    container_name: db
    environment:
      - POSTGRES_DB=picturepoker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    restart: always
  app:
    build: .
    image: luigipoker.azurecr.io/app
    container_name: app
    expose:
      - 8080:8080
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=picturepoker
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - db
  ui:
    build: PicturePokerReact/luigipoker
    image: luigipoker.azurecr.io/ui
    container_name: ui
    ports:
      - 80:80
    depends_on:
      - app